[package]
name = "tuimyface"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
biblatex="0.6"
tui = "0.18"
crossterm = "0.23"
